version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TESTALL_MCSP_1280Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: rimabarman
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/vijetadixit
  gitUsername: rimabarman
  gitBranch: Test2
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: SIQAJDBCAdapterTests
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBNewInsert1
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:Test_DB
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:AlertsCRTAndERT
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:Call_TPP
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:Call_refData
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.referencedata:refData
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:Copy_Call_refData
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:Copy_EdgeFlowserviceWithExistingEdS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:EdgeFlowserviceWithExistingEdS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQA_E2E_Mon_Test
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQA_ThirdPPEdgeFS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:Basic_Flow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.math:multiplyIntList
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: Basics_1:mapservice
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:TryCatch
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Map_1:TestFlow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: REST_1_1.CurrentDateAndTime:_get
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: SOAP_1_1:showDateAndTime
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: services:addInts
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_testall_mcsp_1280.integrations:Sum
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_testall_mcsp_1280.integrations:deepclonetest
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
configurationVariables:
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : siqatest
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : 9.46.196.248
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MySQL
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Driver_test
  ? artConnection.SIQA_TESTALL_MCSP_1280Project.project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
