version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TESTALL_MCSP_1280Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_testall_mcsp_1280.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBNewInsert1
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: project.siqa_testall_mcsp_1280.integrations:AlertsCRTAndERT
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:EdgeFlowserviceWithExistingEdS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQA_E2E_Mon_Test
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_testall_mcsp_1280.integrations:SIQA_ThirdPPEdgeFS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_TESTALL_MCSP_1280Project
    version: "1.0"
- serviceName: services:addInts
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
